### ISSUE TITLE
Error: invalid type: integer `224`, expected an array of length 2

### ISSUE THREAD

**Issue by geocine** [pykeio/diffusers#6]
From documentation I converted the SD1.5 model as follows:

To convert a float32 model from HF (recommended for CPU inference):
```sh
 python3 scripts/hf2pyke.py runwayml/stable-diffusion-v1-5 ~/pyke-diffusers-sd15/
```

Then I ran the https://github.com/pykeio/diffusers/blob/main/examples/stable-diffusion.rs 

May `Cargo.toml` looks like this

```toml
[dependencies]
pyke-diffusers = "0.1"
```

**Comment by sudo-carson** [comment]
Sorry, I won't be able to fix this issue for another few hours, but the issue is on line 379 of `hf2pyke.py`. I believe the end should read `else [crop, crop]`, and the same may be true for line 378 (the end should say `else [size, size]`). Could you try both of those patches and reconverting the model and see if that fixes it?

**Comment by geocine** [comment]
Yes the error is gone
